#if !defined(EVALUATE_INCLUDED)
#  define    EVALUATE_INCLUDED
 
#  define                                 MAXO           (8)
#  define                            BAD_TRADE         (100)
#  define                          EIGHT_PAWNS          (10)
#  define                        PAWNS_BLOCKED          (12)
#  define                  CENTER_PAWN_UNMOVED          (16)
#  define                             PAWN_DUO           (2)
#  define                             PAWN_JAM          (10)
#  define                         PAWN_DOUBLED           (5)
#  define                         PAWN_WEAK_P1          (10)
#  define                         PAWN_WEAK_P2          (15)
#  define                          PAWN_PASSED           (5)
#  define           PAWN_PROTECTED_PASSER_WINS          (25)
#  define                      PAWN_RP_PENALTY          (12)
 
#  define                          PAWN_BASE_A          (-2)
#  define                          PAWN_BASE_B           (0)
#  define                          PAWN_BASE_C           (2)
#  define                          PAWN_BASE_D           (4)
#  define                          PAWN_BASE_E           (4)
#  define                          PAWN_BASE_F           (2)
#  define                          PAWN_BASE_G           (0)
#  define                          PAWN_BASE_H          (-2)

#  define                       PAWN_ADVANCE_A           (1)
#  define                       PAWN_ADVANCE_B           (1)
#  define                       PAWN_ADVANCE_C           (2)
#  define                       PAWN_ADVANCE_D           (2)
#  define                       PAWN_ADVANCE_E           (2)
#  define                       PAWN_ADVANCE_F           (2)
#  define                       PAWN_ADVANCE_G           (1)
#  define                       PAWN_ADVANCE_H           (1)
 
#  define                    PAWN_ADVANCE_BC_A          (-2)
#  define                    PAWN_ADVANCE_BC_B          (-2)
#  define                    PAWN_ADVANCE_BC_C           (1)
#  define                    PAWN_ADVANCE_BC_D           (1)
#  define                    PAWN_ADVANCE_BC_E           (1)
#  define                    PAWN_ADVANCE_BC_F           (1)
#  define                    PAWN_ADVANCE_BC_G          (-2)
#  define                    PAWN_ADVANCE_BC_H          (-2)

#  define                    PAWN_ADVANCE_EG_A           (1)
#  define                    PAWN_ADVANCE_EG_B           (1)
#  define                    PAWN_ADVANCE_EG_C           (1)
#  define                    PAWN_ADVANCE_EG_D           (2)
#  define                    PAWN_ADVANCE_EG_E           (2)
#  define                    PAWN_ADVANCE_EG_F           (1)
#  define                    PAWN_ADVANCE_EG_G           (1)
#  define                    PAWN_ADVANCE_EG_H           (1)

#  define          PAWN_CONNECTED_PASSED_6TH  (PAWN_VALUE/2)
#  define              PAWN_CONNECTED_PASSED             (8)
  
#  define          PAWN_SUPPORTED_PASSED_RANK2           (0)
#  define          PAWN_SUPPORTED_PASSED_RANK3           (0)
#  define          PAWN_SUPPORTED_PASSED_RANK4           (0)
#  define          PAWN_SUPPORTED_PASSED_RANK5           (6)
#  define          PAWN_SUPPORTED_PASSED_RANK6          (30)
#  define          PAWN_SUPPORTED_PASSED_RANK7          (50)

#  define                    KING_KING_TROPISM           (7)
  
#  define                       BISHOP_TRAPPED         (150)
#  define           BISHOP_PLUS_PAWNS_ON_COLOR           (1)
#  define           BISHOP_OVER_KNIGHT_ENDGAME          (10)
#  define                      BISHOP_MOBILITY           (1)
#  define                          BISHOP_PAIR          (25)
#  define                   BISHOP_KING_SAFETY          (20)
  
#  define                          ROOK_ON_7TH          (15)
#  define                    ROOK_ABSOLUTE_7TH          (20)
#  define              ROOK_CONNECTED_7TH_RANK           (5)
#  define                       ROOK_OPEN_FILE          (12)
#  define                  ROOK_HALF_OPEN_FILE           (6)
#  define             ROOK_CONNECTED_OPEN_FILE           (8)
#  define              ROOK_BEHIND_PASSED_PAWN          (12)
#  define                         ROOK_TRAPPED          (20)
  
#  define               QUEEN_ROOK_ON_7TH_RANK          (10)
#  define                    QUEEN_KING_SAFETY           (6)
#  define                     QUEEN_VS_2_ROOKS          (60)
#  define                      QUEEN_IS_STRONG          (30)
 
#  define                KING_SAFETY_MATE_G2G7           (3)
#  define              KING_SAFETY_MATE_THREAT         (600)
#  define                       KING_BACK_RANK           (2)
#  define                KING_SAFETY_STONEWALL           (6)
#  define                   KING_SAFETY_CLOSED           (5)
#  define                KING_SAFETY_OPEN_FILE           (4)
 
 
#  define                 DEVELOPMENT_THEMATIC           (3)
#  define                  DEVELOPMENT_UNMOVED           (3)
#  define                  BLOCKED_CENTER_PAWN          (12)
#  define            DEVELOPMENT_LOSING_CASTLE          (12)
#  define              DEVELOPMENT_NOT_CASTLED          (24)
#  define              DEVELOPMENT_QUEEN_EARLY           (8)
 
#endif
