#if !defined(EVALUATE_INCLUDED)
#  define    EVALUATE_INCLUDED
 
#  define                                 DRAW           (0)

#  define           ROOK_BISHOP_VS_ROOK_KNIGHT         (200)

#  define                             PAWN_RAM          (25)
#  define                         BAD_PAWN_RAM          (50)
#  define                        PAWN_ISOLATED         (100)
#  define                         PAWN_DOUBLED          (50)
#  define                         PAWN_WEAK_P0         (200)
#  define                         PAWN_WEAK_P1         (250)
#  define                         PAWN_WEAK_P2         (300)
#  define                           PAWN_LOOSE         (100)
#  define                          PAWN_PASSED         (125)
#  define                   PAWN_HIDDEN_PASSED         (300)
#  define                   PAWN_PASSED_ON_7TH         (400)
#  define           PAWN_PROTECTED_PASSER_WINS         (300)
 
#  define                       PAWN_ADVANCE_A         (-20)
#  define                       PAWN_ADVANCE_B         (-15)
#  define                       PAWN_ADVANCE_C          (-5)
#  define                       PAWN_ADVANCE_D           (5)
#  define                       PAWN_ADVANCE_E           (5)
#  define                       PAWN_ADVANCE_F         (-10)
#  define                       PAWN_ADVANCE_G         (-15)
#  define                       PAWN_ADVANCE_H         (-20)
 
#  define                    PAWN_ADVANCE_BC_A         (-10)
#  define                    PAWN_ADVANCE_BC_B         (-10)
#  define                    PAWN_ADVANCE_BC_C           (5)
#  define                    PAWN_ADVANCE_BC_D          (10)
#  define                    PAWN_ADVANCE_BC_E          (10)
#  define                    PAWN_ADVANCE_BC_F         (-10)
#  define                    PAWN_ADVANCE_BC_G         (-50)
#  define                    PAWN_ADVANCE_BC_H         (-50)

#  define                    PAWN_ADVANCE_KING          (15)
  
#  define                    PAWN_ADVANCE_EG_A          (10)
#  define                    PAWN_ADVANCE_EG_B          (10)
#  define                    PAWN_ADVANCE_EG_C          (10)
#  define                    PAWN_ADVANCE_EG_D          (10)
#  define                    PAWN_ADVANCE_EG_E          (10)
#  define                    PAWN_ADVANCE_EG_F          (10)
#  define                    PAWN_ADVANCE_EG_G          (10)
#  define                    PAWN_ADVANCE_EG_H          (10)

#  define          PAWN_CONNECTED_PASSED_RANK2          (10)
#  define          PAWN_CONNECTED_PASSED_RANK3          (25)
#  define          PAWN_CONNECTED_PASSED_RANK4          (50)
#  define          PAWN_CONNECTED_PASSED_RANK5         (100)
#  define          PAWN_CONNECTED_PASSED_RANK6         (200)
#  define          PAWN_CONNECTED_PASSED_RANK7         (400)
#  define          PAWN_CONNECTED_PASSED_SIXTH        (1000)
  
#  define          PAWN_SUPPORTED_PASSED_RANK2           (0)
#  define          PAWN_SUPPORTED_PASSED_RANK3           (0)
#  define          PAWN_SUPPORTED_PASSED_RANK4           (0)
#  define          PAWN_SUPPORTED_PASSED_RANK5         (100)
#  define          PAWN_SUPPORTED_PASSED_RANK6         (300)
#  define          PAWN_SUPPORTED_PASSED_RANK7         (500)

#  define                  KNIGHT_KING_TROPISM           (6)
#  define                  BISHOP_KING_TROPISM           (4)
#  define                    ROOK_KING_TROPISM          (10)
#  define                   QUEEN_KING_TROPISM          (10)
  
#  define                       KNIGHT_TRAPPED        (2000)
#  define                       KNIGHT_OUTPOST         (100)
  
#  define                       BISHOP_TRAPPED        (1500)
#  define                      BISHOP_MOBILITY          (12)
#  define                          BISHOP_PAIR         (200)
  
#  define                          ROOK_ON_7TH         (200)
#  define                    ROOK_ABSOLUTE_7TH         (300)
#  define              ROOK_CONNECTED_7TH_RANK         (100)
#  define                       ROOK_OPEN_FILE         (100)
#  define             ROOK_CONNECTED_OPEN_FILE          (50)
#  define                  ROOK_HALF_OPEN_FILE          (25)
#  define              ROOK_BEHIND_PASSED_PAWN          (50)
#  define                         ROOK_TRAPPED         (300)
#  define               ROOK_ATTACK_WEAK_PAWNS          (25)
  
#  define                      QUEEN_IS_STRONG         (100)
#  define               QUEEN_ROOK_ON_7TH_RANK         (200)
 
#  define                    ACCEPTABLE_FAULTS           (5)
 
#  define              KING_SAFETY_GOOD_BISHOP           (8)
#  define                KING_SAFETY_OPEN_FILE           (6)
#  define                       KING_BACK_RANK          (50)
#  define               KING_SAFETY_NOT_CORNER           (2)
#  define                KING_SAFETY_IN_CORNER           (2)
#  define              KING_SAFETY_PAWN_ATTACK           (4)
#  define        KING_SAFETY_PAWN_ATTACK_CLOSE           (6)
 
#  define                  KING_SAFETY_RP_ADV1           (2)
#  define                  KING_SAFETY_RP_ADV2           (5)
#  define               KING_SAFETY_RP_TOO_FAR           (8)
#  define               KING_SAFETY_RP_MISSING          (10)
#  define             KING_SAFETY_RP_FILE_OPEN           (6)
 
#  define                  KING_SAFETY_NP_ADV1           (5)
#  define                  KING_SAFETY_NP_ADV2           (8)
#  define               KING_SAFETY_NP_TOO_FAR          (11)
#  define               KING_SAFETY_NP_MISSING          (14)
#  define             KING_SAFETY_NP_FILE_OPEN           (6)
 
#  define                  KING_SAFETY_BP_ADV1           (2)
#  define                  KING_SAFETY_BP_ADV2           (4)
#  define               KING_SAFETY_BP_TOO_FAR           (6)
#  define               KING_SAFETY_BP_MISSING           (6)
#  define             KING_SAFETY_BP_FILE_OPEN           (4)
 
#  define                 DEVELOPMENT_THEMATIC          (50)
#  define             DEVELOPMENT_BLOCKED_PAWN         (150)
#  define           DEVELOPMENT_UNMOVED_PIECES         (100)
#  define            DEVELOPMENT_UNMOVED_PAWNS         (100)
#  define              DEVELOPMENT_QUEEN_EARLY         (100)
#  define            DEVELOPMENT_LOSING_CASTLE         (200)
#  define              DEVELOPMENT_NOT_CASTLED         (150)
 
#  define                         TRADE_PIECES           (5)
#  define                          TRADE_PAWNS          (15)

#endif
