#!/bin/csh
if ($# < 1) then
  echo "version number missing"
  exit(1)
endif
echo "releasing crafty version $1"
rm *.zip *.Z *.gz
zip crafty-$1.zip *.c *.h *.s *.cpp Makefile Makefile.nt
rcp crafty-$1.zip juniper:/nc/pub/hyatt/v16
rm crafty-$1.zip
tar -cvf crafty-$1.tar *.c *.h *.s *.cpp Makefile Makefile.nt
gzip crafty-$1.tar
rcp crafty-$1.tar.gz juniper:/nc/pub/hyatt/v16
rm crafty-$1.tar.gz
